### ISSUE TITLE
Any chance of ssc323 compatibility?

### ISSUE THREAD

**Issue by danergo** [linux-chenxing/linux-chenxing-vendor-slop#1]
I have a device with SSC323 which has not too much info available online.

I'd like to have HW watchdog which needs some kernel mods.
Is there any chance that I can use this kernel with SSC323 chip?

Thank you.

**Comment by fifteenhex** [comment]
Sorry I didn't get a notification.

As far as I know all of the SSC3xx chips should work with the kernel sources that are here and other places.
I can't tell you how to use it though as I have only been using the code as a reference.
